global:
  scrape_interval: 5s
  external_labels:
    monitor: 'product-microservice' 

scrape_configs:
  - job_name: 'product-microservice'
    scrape_interval: 4s
    static_configs:
      - targets: ['localhost:$PORT']